#!/usr/bin/make -f
# Makefile for ACE #
# ---------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = a-comp

# --------------------------------------------------------------
# Files to build

FILES = \
	$(NAME).c

# --------------------------------------------------------------
# Extra params

HAS_PRESETS = true
HAS_STEREO = true

# --------------------------------------------------------------
# Do some magic

include ../../Makefile.plugins.mk

# --------------------------------------------------------------
